from ._internal.exceptions import RedisBaseError

__all__ = ("RedisBaseError",)
